name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login Docker Hub
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: docker login -u $username -p $password
    
    - name: Build the Docker image
      run:  docker build -t udagram-api-feed ./udagram-api-feed
      
    - name: Build the Docker tag
      run:  docker tag udagram-api-feed uyennguyen0721/udagram-api-feed:v1
      
    - name: Docker push
      run:  docker push uyennguyen0721/udagram-api-feed:v1
